(()=>{
'use strict';
const $=id=>document.getElementById(id),scene=new FactoryScene($('world'));
let model=null,scenario='gentle',paused=false,speed=1,muted=false,acc=0,last=performance.now(),uiClock=0,audio=null,endingShown=false,overlayPaused=false;
let history=[];try{muted=localStorage.getItem('strike-muted')==='true';history=JSON.parse(localStorage.getItem('strike-history')||'[]');if(!Array.isArray(history))history=[];}catch{}
const cards=Strike.cards;
function feedback(s){$('feedback').textContent=s;}
function beep(kind=0){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),gain=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(kind?523:330,audio.currentTime);o.frequency.exponentialRampToValueAtTime(kind?784:440,audio.currentTime+.12);gain.gain.setValueAtTime(.022,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.3);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.3);}catch{feedback('瀏覽器未提供音訊，遊戲可照常進行。');}}
const clock=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
cards.forEach(c=>{const b=document.createElement('button');b.className=`action ${c.side}`;b.id=`action-${c.id}`;b.title=c.tip;b.setAttribute('aria-label',c.name);b.innerHTML=`<span class="icon">${c.icon}</span><b>${c.name}</b><small>準備就緒</small><span class="coolbar"></span>`;b.addEventListener('mouseenter',()=>feedback(c.tip));b.addEventListener('focus',()=>feedback(c.tip));b.addEventListener('click',()=>{if(!model)return feedback('先選擇情境，再公布財報。');if(paused||overlayPaused)return feedback('目前暫停中，按「繼續」後才能使用事件卡。');let r=model.act(c.id);feedback(r.message);if(r.ok)beep();renderUI();});$('actions').appendChild(b);});
function setPause(value){paused=value;$('pause').textContent=paused?'繼續':'暫停';$('pause-banner').hidden=!paused||!model||!!model.result;last=performance.now();renderUI();}
function modal(id){overlayPaused=true;$(id).showModal();}
function closeModal(id){$(id).close();overlayPaused=false;last=performance.now();}
function choose(){model=null;endingShown=false;paused=false;acc=0;speed=1;$('pause-banner').hidden=true;$('speed').textContent='速度 1×';$('pause').textContent='暫停';modal('welcome');renderUI();}
function start(){model=new Strike.Model(scenario);scene.people.forEach((a,i)=>{a.x=325+(i%15)*42;a.y=358+Math.floor(i/15)*22;});endingShown=false;paused=false;speed=1;acc=0;last=performance.now();closeModal('welcome');beep(1);feedback('財報公布了！你可以幫任何一邊，也可以先觀察。');renderUI();}
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{scenario=b.dataset.scenario;document.querySelectorAll('[data-scenario]').forEach(x=>x.classList.toggle('selected',x===b));});
$('start').onclick=start;
$('pause').onclick=()=>{if(!model||model.result)return feedback('開始新局後即可暫停。');setPause(!paused);};$('resume').onclick=()=>setPause(false);
$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`速度 ${speed}×`;feedback(`已切換 ${speed} 倍速，事件與冷卻一起改變速度。`);};
$('sound').onclick=()=>{muted=!muted;try{localStorage.setItem('strike-muted',String(muted));}catch{}$('sound').textContent=`聲音：${muted?'關':'開'}`;if(!muted)beep();};
$('help').onclick=()=>modal('rules');$('close-help').onclick=()=>closeModal('rules');
$('restart').onclick=()=>{if(model)modal('confirm-restart');else choose();};$('cancel-restart').onclick=()=>closeModal('confirm-restart');$('confirm-new').onclick=()=>{closeModal('confirm-restart');choose();};
$('again').onclick=()=>{closeModal('ending');choose();};
for(const id of ['rules','confirm-restart'])$(id).addEventListener('cancel',e=>{e.preventDefault();closeModal(id);});for(const id of ['welcome','ending'])$(id).addEventListener('cancel',e=>e.preventDefault());
document.addEventListener('visibilitychange',()=>{if(document.hidden&&model&&!model.result){setPause(true);feedback('已因切換分頁自動暫停。回來後按「繼續」。');}});
function renderUI(){ $('sound').textContent=`聲音：${muted?'關':'開'}`;if(!model){$('clock').textContent='00:00 / 08:00';return;}let m=model,s=m.score(),terms=m.terms();$('clock').textContent=`${clock(m.time)} / 08:00`;$('phase').textContent=m.result?'本局落幕':m.time<20?'財報發布':m.time<300?'集結與協商':'提案表決';$('scenario-label').textContent=Strike.scenarios[m.scenario].name;$('headline').textContent=m.logs[0]?.text||'';$('workers').textContent=`${Math.round(m.participation*60)} / 60`;$('production').textContent=`${Math.round(m.production*100)}%`;$('solidarity').textContent=`${Math.round(m.support)}%`;$('fatigue').textContent=`${Math.round(m.fatigue)}%`;$('pressure').textContent=`${Math.round(m.pressure)}%`;$('score').textContent=s;$('score-fill').style.width=s+'%';$('salary').textContent=terms.salary+'%';$('bonus').textContent=terms.bonus+' 個月';$('leave').textContent=terms.leave+' 天';$('acceptance').textContent=`預估贊成 ${Math.round(m.acceptance())}% ／ 過半才通過。${m.time<300?'5 分鐘起定期表決。':'每 30 秒再次表決。'}`;$('events').replaceChildren(...m.logs.slice(0,6).map(e=>{let li=document.createElement('li'),time=document.createElement('time');time.textContent=clock(e.time);li.append(time,document.createTextNode(e.text));return li;}));cards.forEach(c=>{let b=$('action-'+c.id),cd=Math.max(0,(m.cooldowns[c.id]||0)-m.time);b.setAttribute('aria-disabled',String(!!cd||paused||overlayPaused||!!m.result));b.querySelector('small').textContent=m.result?'本局已結束':paused?'暫停中':cd?`冷卻 ${Math.ceil(cd)} 秒`:'準備就緒';b.querySelector('.coolbar').style.width=(cd/20*100)+'%';});
if(m.result&&!endingShown){endingShown=true;showEnding();}}
function showEnding(){const m=model;let titles={labor:'這次，大家真的有份！',company:'產線復工，資方守住了。',compromise:'雙方都宣布：我們贏了！',unfinished:'今晚，還沒談完。'};let copy={labor:'員工把帽子拋向天空。新待遇公告貼上廠門，復工旗子也換了顏色。',company:'員工接受較低條件、陸續回到產線。主管舉杯，營收看板繼續往上。',compromise:'兩邊握了手，各自回去宣布重大成果。究竟誰比較開心，就看你站哪邊。',unfinished:'最後提案未獲多數支持。沒有強行宣布勝利，協商留待下一次。'};$('ending-tag').textContent={labor:'勞方勝利',company:'資方勝利',compromise:'折衷協議',unfinished:'協商未完'}[m.result];$('ending-title').textContent=titles[m.result];$('ending-copy').textContent=copy[m.result];$('ending-score').textContent=`協商成果 ${m.score()} 分 · 贊成 ${Math.round(m.acceptance())}%`;$('turning-points').replaceChildren(...[...m.logs].sort((a,b)=>b.weight-a.weight).slice(0,3).sort((a,b)=>a.time-b.time).map(e=>{let li=document.createElement('li');li.textContent=`${clock(e.time)} ${e.text}`;return li;}));$('helped').textContent=`你的干預：勞方 ${m.helped.labor} 次、資方 ${m.helped.company} 次、雙向 ${m.helped.mixed} 次。`;history.unshift({result:m.result,score:m.score(),scenario:m.scenario,date:new Date().toISOString()});history=history.slice(0,20);try{localStorage.setItem('strike-history',JSON.stringify(history));}catch{feedback('本機儲存不可用，本局結果仍可查看。');}beep(1);setTimeout(()=>{if(model===m&&m.result&&!$('ending').open)modal('ending');},1600);}
function frame(now){let dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;if(model&&!paused&&!overlayPaused&&!model.result){acc+=dt*speed;while(acc>=.1){model.step(.1);acc-=.1;}}scene.draw(model,dt,(paused||overlayPaused)&&!model?.result);uiClock+=dt;if(uiClock>.12){uiClock=0;renderUI();}requestAnimationFrame(frame);}
window.strikeView=()=>({model:model?.snapshot(),paused,speed,muted,overlayPaused,actors:scene.people.map(p=>({x:p.x,y:p.y}))});
// Test-only simulation acceleration; no forced winner and no state overrides.
if(new URLSearchParams(location.search).has('qa'))window.strikeQA={advance(seconds){if(!model||paused||overlayPaused)throw Error('Game not running');for(let i=0;i<seconds*10&&!model.result;i++)model.step(.1);renderUI();return model.snapshot();}};
choose();requestAnimationFrame(frame);
})();

